### ISSUE TITLE
Test issue for image location

### ISSUE THREAD

**Issue by cristidregan** [Ometria/ometria.android_sdk#1]
![Screenshot 2020-08-13 at 16 47 21](https://user-images.githubusercontent.com/8706456/91582697-d51c0a80-e958-11ea-96eb-46f0d49c3d59.png)

**Comment by hraban** [comment]
can we close this issue? :)

**Comment by cristidregan** [comment]
@hraban Can you delete it?

**Comment by hraban** [comment]
no worries, happy to leave it closed as-is. thanks!
